from .criteria cimport (
    ClassificationCriteria,
    RegressionCriteria,
    Criteria,
    GiniIndex,
    Entropy,
    SquaredError,
    PartialLinear,
    PartialQuadratic,
    MultiSquaredError,
    PairwiseEuclideanDistance,
    Criteria_DG,
    RegressionCriteria_DG,
    MaximinSquaredError,
    Criteria_DG_Global,
    RegressionCriteria_DG_Global,
    MaximinSquaredError_Global,
)
